export type WorkCategorySlug =
  | 'music-videos'
  | 'films'
  | 'series'
  | 'sports'
  | 'events'

export type WorkRelationship = 'original' | 'collaboration' | 'client'

export type WorkProject = {
  slug: string
  title: string
  category: WorkCategorySlug
  categoryLabel: string
  relationship: WorkRelationship
  creditLabel: string
  client: string
  image: string
  // Sized-down variant for the native <video poster> attribute.
  poster?: string
  alt: string
  objectPosition?: string
  year: string
  // Either a YouTube id for embedded projects or a local video path for
  // films hosted on the site itself.
  youtubeId?: string
  video?: string
  // Short muted loop that plays while the card is hovered.
  hoverClip?: string
  serviceHref: string
  summary: string
  credits: string[]
}

export type ShotAtVibeshackItem = {
  slug: string
  title: string
  client: string
  detail: string
  relationship: WorkRelationship
  creditLabel: string
  playback: 'hosted' | 'youtube'
  collection: 'podcasts' | 'creative-productions'
  youtubeId: string
  image: string
  alt: string
  objectPosition?: string
  hoverClip?: string
}

export const featuredWorkProject: WorkProject = {
  slug: 'body-is-tea',
  title: 'Body Is Tea',
  category: 'music-videos',
  categoryLabel: 'Music Video',
  relationship: 'original',
  creditLabel: 'VibeShack Original',
  client: 'Varii x Josh Sidhu',
  image: '/studio-images/work-body-is-tea-dancers-v20260716.jpg',
    hoverClip: '/studio-videos/work-hover-body-is-tea-v20260716.mp4',
  alt: 'Dancer mid-move in front of red lowriders in the Body Is Tea music video',
  objectPosition: 'center',
  year: '2026',
  youtubeId: '3Rbir7bu408',
  serviceHref: '/video-production/',
  summary:
    'A summer-soaked music video for Varii and Josh Sidhu: lowriders, dancers, and golden-hour driveways, presented by VibeShack Studios.',
  credits: ['A VibeShack Original', 'Directed by Gill'],
}

export const workProjects: WorkProject[] = [
  {
    slug: 'the-buzzer',
    title: 'The Buzzer',
    category: 'series',
    categoryLabel: 'Series',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    client: 'Silicon Mania',
    image: '/studio-images/work-the-buzzer-set-v20260716.jpg',
    hoverClip: '/studio-videos/work-hover-the-buzzer-v20260716.mp4',
    alt: 'A founder pitches an investor across the buzzer table on the Silicon Mania set',
    year: '2026',
    youtubeId: '3mLFnCovlF8',
    serviceHref: '/video-production/',
      summary:
      'A pitch show where founders pitch real investors, and the investors hold a buzzer that can end the meeting. Shot on a clean white set at VibeShack.',
    credits: ['A Silicon Mania production', 'Filmed by VibeShack Studios'],
  },
  {
    slug: 'wing-battle',
    title: 'Wing Battle',
    category: 'events',
    categoryLabel: 'Event Film',
    relationship: 'client',
    creditLabel: 'Post-production by VibeShack',
    client: "Melinda's Foods",
    image: '/studio-images/work-wing-battle-toast-v20260717.jpg',
    hoverClip: '/studio-videos/work-hover-wing-battle-v20260717.mp4',
    alt: "A competitor raises a drink outside the bar at Melinda's Wing Battle",
    year: '2025',
    youtubeId: 'tX5nk9EEBHs',
    serviceHref: '/video-production/',
    summary:
      "Post-production for Melinda's Hot Sauce Wing Battle in Hayward, CA, shaping pit smoke, hot sauce, competitors, and the crown into the final event film.",
    credits: ['Post-production by VibeShack Studios', "A Melinda's Hot Sauce event"],
  },
  {
    slug: 'damian-stone',
    title: 'Damian Stone',
    category: 'sports',
    categoryLabel: 'Sports Film',
    relationship: 'original',
    creditLabel: 'VibeShack Original',
    client: 'Oakland Ballers',
    image: '/studio-images/work-damian-stone-gloves-v20260716.jpg',
    hoverClip: '/studio-videos/work-hover-damian-stone-v20260716.mp4',
    alt: 'Damian Stone pulls on his batting gloves in the dugout',
    year: '2026',
    youtubeId: 'i-YfBQia7UI',
    serviceHref: '/video-production/',
      summary:
      'A hype film for Oakland Ballers pitcher Damian Stone: pre-game ritual and locker-room texture, shot for game-day focus.',
    credits: ['A VibeShack Original', 'Featuring Damian Stone of the Oakland Ballers'],
  },
  {
    slug: 'damian-stone-feature',
    title: 'Damian Stone: Player Feature',
    category: 'sports',
    categoryLabel: 'Player Feature',
    relationship: 'original',
    creditLabel: 'VibeShack Original',
    client: 'Oakland Ballers',
    image: '/studio-images/work-damian-stone-feature-v20260716.jpg',
    hoverClip: '/studio-videos/work-hover-damian-stone-feature-v20260716.mp4',
    alt: 'Damian Stone jogging across the outfield in his Oakland Ballers uniform',
    year: '2026',
    youtubeId: 'WWF3sDSyLJw',
    serviceHref: '/video-production/',
      summary:
      'A sit-down player feature with Oakland Ballers pitcher Damian Stone, cut between the interview chair and the ballpark.',
    credits: ['A VibeShack Original', 'Directed by Akar', 'Featuring Damian Stone of the Oakland Ballers'],
  },
  {
    slug: 'evil-eye',
    title: 'Evil Eye',
    category: 'music-videos',
    categoryLabel: 'Music Video',
    relationship: 'original',
    creditLabel: 'VibeShack Original',
    client: 'Varii',
    image: '/studio-images/work-evil-eye-hummer-v20260716.jpg',
    hoverClip: '/studio-videos/work-hover-evil-eye-v20260716.mp4',
    alt: "Varii in front of a white Hummer's light bar at night",
    year: '2026',
    youtubeId: 'uNwd86wwgtc',
    serviceHref: '/video-production/',
      summary:
      'Varii at night: a white Hummer under hard light, with red typography cut over the San Francisco skyline.',
    credits: ['A VibeShack Original', 'Night exteriors across San Francisco'],
  },
  {
    slug: 'chilled',
    title: 'Chilled',
    category: 'music-videos',
    categoryLabel: 'Music Video',
    relationship: 'original',
    creditLabel: 'VibeShack Original',
    client: 'TeYo',
    image: '/studio-images/work-chilled-teyo-v20260716.jpg',
    hoverClip: '/studio-videos/work-hover-chilled-v20260716.mp4',
    alt: 'Two friends on rooftop couches over a foggy San Francisco skyline in the Chilled music video',
    year: '2025',
    youtubeId: 'Y5GQGx1gbPE',
    serviceHref: '/video-production/',
    summary:
      'A night-drifting music video for TeYo: rooftop couches above a foggy skyline, empty streets, and a city cooling down after dark.',
    credits: ['A VibeShack Original', 'Produced with Opale and Zen Studios', 'Directed by Eden Moshe'],
  },
  {
    slug: 'the-client',
    title: 'The Client',
    category: 'films',
    categoryLabel: 'Short Film',
    relationship: 'original',
    creditLabel: 'VibeShack Original',
    client: 'The Babysitters',
    image: '/studio-images/work-the-client-bar-v20260716.jpg',
    poster: '/studio-images/poster-work-the-client-bar-v20260716.jpg',
    hoverClip: '/studio-videos/work-hover-the-client-v20260716.mp4',
    alt: 'The client and the fixer across a candlelit reading table in a neon bar',
    objectPosition: 'center 22%',
    year: '2026',
    video: '/studio-videos/film-the-client-v20260716.mp4',
    serviceHref: '/video-production/',
    summary:
      'An action short made for the SF 48 Hour Film Competition: a client, a fixer, and a card reading in a neon-lit bar. Part of The Babysitters.',
    credits: ['A VibeShack Original', 'Directed by Tay and Victor Li', 'Cinematography by Kylan Philipina and Breton'],
  },
  {
    slug: 'note-to-self',
    title: 'Note To Self',
    category: 'music-videos',
    categoryLabel: 'Visualizer',
    relationship: 'original',
    creditLabel: 'VibeShack Original',
    client: '97Shadd',
    image: '/studio-images/work-note-to-self-desk-v20260716.jpg',
    alt: '97Shadd at a desk under green and red neon in the Note To Self video',
    year: '2026',
    youtubeId: 'Ytvv1tTrvyI',
    hoverClip: '/studio-videos/work-hover-note-to-self-v20260716.mp4',
    serviceHref: '/video-production/',
    summary:
      "A neon studio session for 97Shadd's Note To Self: one desk, one late night, and the route out written across the frame.",
    credits: ['A VibeShack Original', 'Directed and shot by Tay', 'Edited by Erevnaa'],
  },
  {
    slug: 'the-giver',
    title: 'The Giver',
    category: 'music-videos',
    categoryLabel: 'Music Video',
    relationship: 'original',
    creditLabel: 'VibeShack Original',
    client: '97Shadd',
    image: '/studio-images/work-the-giver-portrait-v20260716.jpg',
    poster: '/studio-images/poster-work-the-giver-portrait-v20260716.jpg',
    alt: '97Shadd in a yellow cap mid-verse in The Giver music video',
    year: '2026',
    video: '/studio-videos/film-the-giver-v20260717.mp4',
    hoverClip: '/studio-videos/work-hover-the-giver-v20260716.mp4',
    serviceHref: '/video-production/',
    summary:
      'A music video for the Note To Self outro: a lone figure on a projected stage, planes on the runway, and the words carrying the weight.',
    credits: ['A VibeShack Original', 'Music video for the Note To Self EP'],
  },
  {
    slug: 'betrayed',
    title: 'Betrayed',
    category: 'music-videos',
    categoryLabel: 'Visualizer',
    relationship: 'original',
    creditLabel: 'VibeShack Original',
    client: 'Varii',
    image: '/studio-images/work-betrayed-rider-v20260716.jpg',
    hoverClip: '/studio-videos/work-hover-betrayed-v20260716.mp4',
    alt: 'A rider on a motorcycle under an overpass at night in Betrayed',
    year: '2025',
    youtubeId: 'Lmp5XUxPGYY',
    serviceHref: '/video-production/',
      summary:
      'A moody motorcycle visualizer for Varii, shot at night on San Francisco streets in teal and sodium light.',
    credits: ['A VibeShack Original', 'Directed by Gill'],
  },
]

export const allWorkProjects: WorkProject[] = [featuredWorkProject, ...workProjects]

export function getWorkProject(slug: string) {
  return allWorkProjects.find((project) => project.slug === slug)
}

// Additional client productions and collaborations, linked straight to YouTube.
export const shotAtVibeshack: ShotAtVibeshackItem[] = [
  {
    slug: 'pearl-sitdown-matt-cross',
    title: 'The Sitdown: Matt Cross',
    client: 'Pearl',
    detail: 'Professional PUA Matt Cross joins The Sitdown',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'youtube',
    collection: 'podcasts',
    youtubeId: 'kwK2mkeZBEA',
    image: '/studio-images/shot-at-pearl-matt-cross-v20260722.jpg',
    alt: 'YouTube thumbnail for The Sitdown with Matt Cross, filmed at VibeShack Studios',
  },
  {
    slug: 'how-i-invest-trillion-company',
    title: 'How VCs Find a $1T Company',
    client: 'How I Invest Podcast',
    detail: 'How venture investors find the next trillion-dollar company',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'youtube',
    collection: 'podcasts',
    youtubeId: 'QYCBdiUXTwY',
    image: '/studio-images/shot-at-how-i-invest-trillion-company-v20260722.jpg',
    alt: 'YouTube thumbnail for How VCs Find the Next $1 Trillion Company, filmed at VibeShack Studios',
  },
  {
    slug: 'beyond-tomorrow-agi-control',
    title: 'The AGI Control Problem',
    client: 'The Beyond Tomorrow Podcast',
    detail: 'AGI experts on losing control of artificial intelligence',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'youtube',
    collection: 'podcasts',
    youtubeId: '8JuN6r0u91c',
    image: '/studio-images/shot-at-beyond-tomorrow-agi-control-v20260722.jpg',
    alt: 'YouTube thumbnail for The Beyond Tomorrow Podcast episode about AGI control, filmed at VibeShack Studios',
  },
  {
    slug: 'how-i-invest-future-venture-capital',
    title: '$1T Investor on Venture Capital',
    client: 'How I Invest Podcast',
    detail: 'A trillion-dollar investor on the future of venture capital',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'youtube',
    collection: 'podcasts',
    youtubeId: '6S0pIiPFsNk',
    image: '/studio-images/shot-at-how-i-invest-vc-future-v20260722.jpg',
    alt: 'YouTube thumbnail for a How I Invest Podcast episode about venture capital, filmed at VibeShack Studios',
  },
  {
    slug: 'due-diligence-open-source-ai',
    title: 'Open Source AI vs Big Tech',
    client: 'Due Diligence',
    detail: 'Thomas Wolf of Hugging Face on why open source AI wins',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'youtube',
    collection: 'podcasts',
    youtubeId: 'idECd8RD5DQ',
    image: '/studio-images/shot-at-due-diligence-open-source-ai-v20260722.jpg',
    alt: 'YouTube thumbnail for Due Diligence with Thomas Wolf, filmed at VibeShack Studios',
  },
  {
    slug: 'due-diligence-ai-agents',
    title: 'AI Agents Are Coming for Your Job',
    client: 'Due Diligence',
    detail: 'Flo Crivello of Lindy on the future of AI agents',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'youtube',
    collection: 'podcasts',
    youtubeId: 'WcWpX5ng6Dc',
    image: '/studio-images/shot-at-due-diligence-ai-agents-v20260722.jpg',
    alt: 'YouTube thumbnail for Due Diligence with Flo Crivello, filmed at VibeShack Studios',
  },
  {
    slug: 'beyond-tomorrow-longevity-emergency',
    title: 'Why Death Is Not Treated as an Emergency',
    client: 'The Beyond Tomorrow Podcast',
    detail: 'Longevity experts on treating death like an emergency',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'youtube',
    collection: 'podcasts',
    youtubeId: 'qEqHas2OfQs',
    image: '/studio-images/shot-at-beyond-tomorrow-longevity-death-v20260722.jpg',
    alt: 'YouTube thumbnail for The Beyond Tomorrow Podcast episode about longevity, filmed at VibeShack Studios',
  },
  {
    slug: 'due-diligence-openai-data',
    title: 'Stop Sending Data to OpenAI',
    client: 'Due Diligence',
    detail: 'Sam Hogan of Inference on privacy and AI data',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'youtube',
    collection: 'podcasts',
    youtubeId: 'I13ds2meAj8',
    image: '/studio-images/shot-at-due-diligence-openai-data-v20260722.jpg',
    alt: 'YouTube thumbnail for Due Diligence with Sam Hogan, filmed at VibeShack Studios',
  },
  {
    slug: 'unpaused-infertility-crisis',
    title: 'The Rising Infertility Crisis',
    client: 'Dr. Mary Claire Haver',
    detail: 'Dr. Natalie Crawford on the infertility crisis',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'youtube',
    collection: 'podcasts',
    youtubeId: 'EFNL3qdbuTY',
    image: '/studio-images/shot-at-unpaused-infertility-v20260722.jpg',
    alt: 'YouTube thumbnail for Dr. Mary Claire Haver with Dr. Natalie Crawford, filmed at VibeShack Studios',
  },
  {
    slug: 'powerlaw-investor-roadshow',
    title: 'Powerlaw Investor Roadshow',
    client: 'Powerlaw Corp.',
    detail: 'Powerlaw investor roadshow, June 2026',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'youtube',
    collection: 'creative-productions',
    youtubeId: 'oRKAE4_4G74',
    image: '/studio-images/shot-at-powerlaw-roadshow-v20260722.jpg',
    alt: 'YouTube thumbnail for the Powerlaw Investor Roadshow, filmed at VibeShack Studios',
  },
  {
    slug: 'beyond-tomorrow-aging-disease',
    title: 'Aging Is a Disease',
    client: 'The Beyond Tomorrow Podcast',
    detail: 'A longevity scientist on treating aging as a disease',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'youtube',
    collection: 'podcasts',
    youtubeId: 'x0J437kmXNA',
    image: '/studio-images/shot-at-beyond-tomorrow-aging-disease-v20260722.jpg',
    alt: 'YouTube thumbnail for The Beyond Tomorrow Podcast episode about aging, filmed at VibeShack Studios',
  },
  {
    slug: 'due-diligence-checks-on-vibes',
    title: '$150K Checks on Vibes',
    client: 'Due Diligence',
    detail: 'Hubert Thieblot on making early-stage investments',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'youtube',
    collection: 'podcasts',
    youtubeId: 'KbzKiIvN7Yk',
    image: '/studio-images/shot-at-due-diligence-vibes-v20260722.jpg',
    alt: 'YouTube thumbnail for Due Diligence with Hubert Thieblot, filmed at VibeShack Studios',
  },
  {
    slug: 'beyond-tomorrow-death-engineering',
    title: 'Death as an Engineering Problem',
    client: 'The Beyond Tomorrow Podcast',
    detail: 'Derya Unutmaz on human death as a solvable engineering problem',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'youtube',
    collection: 'podcasts',
    youtubeId: '_VSKX2HYYYE',
    image: '/studio-images/shot-at-beyond-tomorrow-death-engineering-v20260722.jpg',
    alt: 'YouTube thumbnail for The Beyond Tomorrow Podcast with Derya Unutmaz, filmed at VibeShack Studios',
  },
  {
    slug: 'beyond-tomorrow-cuba',
    title: 'Trump, Cuba, and Intervention',
    client: 'The Beyond Tomorrow Podcast',
    detail: 'A Stanford historian on United States policy toward Cuba',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'youtube',
    collection: 'podcasts',
    youtubeId: 'Sha9fECP82U',
    image: '/studio-images/shot-at-beyond-tomorrow-cuba-v20260722.jpg',
    alt: 'YouTube thumbnail for The Beyond Tomorrow Podcast episode about Cuba, filmed at VibeShack Studios',
  },
  {
    slug: 'second-nature-ai-conservation',
    title: 'AI and Conservation Funding',
    client: 'Oxygen Conservation',
    detail: 'Troy Carter on AI companies funding conservation',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'youtube',
    collection: 'podcasts',
    youtubeId: 'wcw1iTPfsBM',
    image: '/studio-images/shot-at-second-nature-ai-conservation-v20260722.jpg',
    alt: 'YouTube thumbnail for Oxygen Conservation with Troy Carter, filmed at VibeShack Studios',
  },
  {
    slug: 'second-nature-carbon-accounting',
    title: 'The Carbon Accounting Shakeout',
    client: 'Oxygen Conservation',
    detail: 'Dimitri Theocharis on the future of carbon accounting companies',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'youtube',
    collection: 'podcasts',
    youtubeId: 'nkpMFBT1zV4',
    image: '/studio-images/shot-at-second-nature-carbon-accounting-v20260722.jpg',
    alt: 'YouTube thumbnail for Oxygen Conservation with Dimitri Theocharis, filmed at VibeShack Studios',
  },
  {
    slug: 'unpaused',
    title: 'unPAUSED',
    client: 'unPAUSED',
    detail: 'Toxins, stress, and your hormones',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'hosted',
    collection: 'podcasts',
    youtubeId: 'ReIQcS8L6Hs',
    image: '/studio-images/work-unpaused-haver-podcast-v20260708.jpg',
    hoverClip: '/studio-videos/work-hover-unpaused-v20260716.mp4',
    alt: 'unPAUSED podcast recording in The Executive at VibeShack Studios',
    objectPosition: '80% center',
  },
  {
    slug: 'second-nature',
    title: 'Second Nature',
    client: 'Second Nature',
    detail: 'The AI world has a human problem',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'hosted',
    collection: 'podcasts',
    youtubeId: 'QMXrpJteBXA',
    image: '/studio-images/work-second-nature-set-v20260716.jpg',
    hoverClip: '/studio-videos/work-hover-second-nature-v20260716.mp4',
    alt: 'Second Nature hosts in conversation on the white set at VibeShack Studios',
  },
  {
    slug: 'vegas-veteran-voices',
    title: 'Vegas Veteran Voices',
    client: 'Vegas Veteran Voices',
    detail: 'The man behind Terminal Lance',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'hosted',
    collection: 'podcasts',
    youtubeId: 'E893IZTGmrQ',
    image: '/studio-images/work-vegas-veteran-voices-v20260709.jpg',
    hoverClip: '/studio-videos/work-hover-vegas-veteran-v20260716.mp4',
    alt: 'Vegas Veteran Voices interview at VibeShack Studios',
  },
  {
    slug: 'scott-stephenson-ai-show',
    title: 'Scott Stephenson AI Show',
    client: 'Scott Stephenson',
    detail: 'Protecting your IP from AI training',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'hosted',
    collection: 'podcasts',
    youtubeId: 'dKY24SpeYKo',
    image: '/studio-images/work-ai-show-host-v20260716.jpg',
    hoverClip: '/studio-videos/work-hover-ai-show-v20260716.mp4',
    alt: 'Scott Stephenson recording the AI Show at VibeShack Studios',
  },
  {
    slug: 'jason-tartick',
    title: 'Jason Tartick',
    client: 'Jason Tartick',
    detail: 'Ross Pomerantz, the BTS of Corporate Bro',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'hosted',
    collection: 'podcasts',
    youtubeId: '4zd17_NxABw',
    image: '/studio-images/work-tartick-corporate-bro-v20260709.jpg',
    hoverClip: '/studio-videos/work-hover-jason-tartick-v20260716.mp4',
    alt: 'Jason Tartick podcast conversation at VibeShack Studios',
  },
  {
    slug: 'gavriella',
    title: 'Gavriella',
    client: 'Gavriella',
    detail: 'Supernova, official music video',
    relationship: 'collaboration',
    creditLabel: 'Co-produced by VibeShack',
    playback: 'hosted',
    collection: 'creative-productions',
    youtubeId: 'J4ZKUYv4JqY',
    image: '/studio-images/work-gavriella-tableau-v20260716.jpg',
    hoverClip: '/studio-videos/work-hover-gavriella-v20260716.mp4',
    alt: 'Gavriella and dancers in a white tableau from the Supernova music video',
  },
  {
    slug: 'varii-ballin-out',
    title: 'Varii',
    client: 'Varii',
    detail: 'Ballin Out, official video',
    relationship: 'client',
    creditLabel: 'Filmed by VibeShack',
    playback: 'hosted',
    collection: 'creative-productions',
    youtubeId: '2nJD5lCXbuo',
    image: '/studio-images/work-ballin-out-court-v20260716.jpg',
    hoverClip: '/studio-videos/work-hover-ballin-out-v20260716.mp4',
    alt: 'Varii on the basketball court in the Ballin Out music video',
  },
]
